env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - go test -v -cover ./pkg/... ./flex/cmd/...
builds:
  - main: ./flex/main.go
    binary: flex
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  -
    name_template: "flex_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - scripts/user/configure-localhost.sh
release:
  github:
    owner: fp-mt-test-org    
    name: devx-workflows
  extra_files:
    - glob: ./scripts/user/install-flex.sh
changelog:
  sort: asc
