# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - go test -v -cover ./pkg/... ./tools/... ./flex/cmd/...
builds:
  - main: ./flex/main.go
    binary: flex
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - format: tar.gz
    files:
      - templates/**/*
release:
  github:
    owner: fp-mt-test-org    
    name: devx-workflows
changelog:
  sort: asc
