name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ./scripts/configure-localhost.sh
    - name: Initial Build
      run:  ./scripts/build-flex.sh
    - name: Flex Build & Test
      run: . ~/.bashrc && flex build-test
