name: DevX CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Dev Dependencies
      run: ./scripts/setup-dev-dependencies.sh
    - name: Initial Build & Unit Test
      run:  ls -la && auto_install=true ./scripts/user/build-flex.sh
    - name: Flex Build & Unit, Feature Test
      run: .devx-workflows/flex build-test
    - name: Publish Release
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} goreleaser release --rm-dist
